[package]
name = "define"
version = "0.1.0"
authors = ["Jesse Preiner <jesse.preiner@yardi.com>"]

[dependencies]
futures = "0.1"
hyper = "0.14"
hyper-tls = "0.1.2"
tokio-core = "0.1"
pretty_env_logger = "0.2.0"
config = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
